#!/bin/sh
# File generated by ocamlbuild

cd /home/synophride/Documents/Projet_PFA

rm -f ast.cmi
rm -f lexer.annot
rm -f lexer.cmi
rm -f lexer.cmx
rm -f lexer.ml
rm -f lexer.o
rm -f parser.annot
rm -f parser.cmi
rm -f parser.cmx
rm -f parser.ml
rm -f parser.mli
rm -f parser.o
rm -f test.cmi
rm -f test.cmo
rm -f test_typage.cmi
rm -f test_typage.cmo
rm -f top.annot
rm -f top.cmi
rm -f top.cmx
rm -f top.o
rm -f typage.annot
rm -f typage.cmi
rm -f typage.cmo
rm -f typage.cmx
rm -f typage.o
# Also clean the script itself
rm -f /home/synophride/Documents/Projet_PFA/_build/sanitize.sh
